management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,mappings,logStats,beans
  endpoint:
    health:
      show-details: always
      show-components: always

  server:
    port: 8081

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

  info:
    git:
      mode: full