management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,mappings,logStats,beans,loggers
  endpoint:
    health:
      show-details: always
      show-components: always

  server:
    port: 8081

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

  info:
    git:
      mode: full
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: @project.name@
    gourpId: @project.groupId@
    artifactId : @project.artifactId@
    version : @project.version@