management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,mappings,logStats
  endpoint:
    health:
      show-details: always
      show-components: always
  server:
    port: 8081